### ISSUE TITLE
Hide the scroll bar on the screenshot

### ISSUE THREAD

**Issue by aplekhanov** [raiyanyahya/snapsht#4]
Hey!

I just wanted to say that your tools are awesome and super helpful. But, I did notice a little issue on macOS. In the screenshot, the scroll bar is visible. Any chance you could fix that?

Thanks a bunch!

![screenshot](https://user-images.githubusercontent.com/1385340/224025662-d7644dcc-07d9-4e79-9483-7e9ba5c1f574.png)

**Comment by raiyanyahya** [comment]
Thank you for the kind words. I will look into the feature and and check of this can actually be done 🤔.

Will keep you posted.

**Comment by raiyanyahya** [comment]
Hi @aplekhanov thank you for the patience! I have released a fix for the scrollbars. Please update to the latest version of the cli. Hope this works for you! Thank you again.
